version: "3.5"

services:
  db:
      image: postgres:12
      environment:
        POSTGRES_USER: orthanc
        POSTGRES_PASSWORD: orthanc
        POSTGRES_DB: orthanc
      ports:
        - "5432:5432"
      volumes:
        - ./database/:/var/lib/postgresql/data/
      restart: unless-stopped
  orthanc:
    image: orthancteam/orthanc
    hostname: orthanc
    volumes:
    
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
 
      - ./db/:/var/lib/orthanc/db/
    ports:
      - "4242:4242" # DICOM
      - "8042:8042" # Web
    restart: unless-stopped
  orthanc-proxy:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
